spring.application.name=MarketPlace

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/E-Commerce-DB
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.security=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=franklinsurya4@gmail.com
spring.mail.password=jowmnmgqrvvyasem
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

festival.offers.scheduler.enabled=true
festival.offers.default-max-discount=5000.0
festival.offers.coupon-prefix=FEST

spring.task.scheduling.pool.size=5

# STORE STATIC DATA
store.adminName=FRANKLIN SURYA S
store.adminPassword=fss123
store.storeName=QualityProducts
store.categories=c
store.currency=INR
store.description=Best e-commerce store for all categories

